### PR TITLE
refactoring and preparing for adding cloudscale

### PR DESCRIPTION
**Pull request by mweibel**
## Summary

* moves all commands from toplevel to a level below `exoscale`. 
* adjusts flags to be relevant for where they belong to
* renames "app" from exoscale-metrics-collector to metrics-collector
* a few small refactorings related to the logger and context passing, and package structure

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

### CODE REVIEW

**Comment by susana-garcia** [comment]
LGTM, but please update the Readme.

**Comment by mweibel** [comment]
readme updated, thx :+1:

**Comment by zugao** [comment]
Since we decided to create a new repository based on this one I really don't see the point to still update this repository. I guess it's ok to make it generic at this point but I would leave it as is and concentrate on a new repo. Would it be fine for you to create the same PR in a new repo?

**Comment by mweibel** [comment]
FTR: we'll rename the current repo once refactoring has been done.

To ensure we could still fix bugs on the non-refactored exoscale metrics collector, I created a new "base" branch for the refactoring called `refactored-collectors` and all PRs will target that new `base` branch.

**Review by zugao — APPROVED** [review]
LGTM

**Pull request merged**
